export default {
  SIGNUP_REQUEST: Symbol('SIGNUP_REQUEST'),
  SIGNUP_SUCCESS: Symbol('SIGNUP_SUCCESS'),
  SIGNUP_FAILURE: Symbol('SIGNUP_FAILURE'),

  LOGIN_REQUEST: Symbol('LOGIN_REQUEST'),
  LOGIN_SUCCESS: Symbol('LOGIN_SUCCESS'),
  LOGIN_FAILURE: Symbol('LOGIN_FAILURE'),

  LOGOUT_REQUEST: Symbol('LOGOUT_REQUEST'),
  LOGOUT_SUCCESS: Symbol('LOGOUT_SUCCESS'),
  LOGOUT_FAILURE: Symbol('LOGOUT_FAILURE'),

  RECEIVE_AUTH_REQUEST: Symbol('RECEIVE_AUTH_REQUEST'),
  RECEIVE_AUTH_SUCCESS: Symbol('RECEIVE_AUTH_SUCCESS'),
  RECEIVE_AUTH_FAILURE: Symbol('RECEIVE_AUTH_FAILURE'),
};
