const getType = key => Symbol(`chats/${key}`);

export default {
  FETCH_MY_CHATS_REQUEST: getType('FETCH_MY_CHATS_REQUEST'),
  FETCH_MY_CHATS_SUCCESS: getType('FETCH_MY_CHATS_SUCCESS'),
  FETCH_MY_CHATS_FAILURE: getType('FETCH_MY_CHATS_FAILURE'),

  FETCH_ALL_CHATS_REQUEST: getType('FETCH_ALL_CHATS_REQUEST'),
  FETCH_ALL_CHATS_SUCCESS: getType('FETCH_ALL_CHATS_SUCCESS'),
  FETCH_ALL_CHATS_FAILURE: getType('FETCH_ALL_CHATS_FAILURE'),

  FETCH_CHAT_REQUEST: getType('FETCH_CHAT_REQUEST'),
  FETCH_CHAT_SUCCESS: getType('FETCH_CHAT_SUCCESS'),
  FETCH_CHAT_FAILURE: getType('FETCH_CHAT_FAILURE'),

  CREATE_CHAT_REQUEST: getType('CREATE_CHAT_REQUEST'),
  CREATE_CHAT_SUCCESS: getType('CREATE_CHAT_SUCCESS'),
  CREATE_CHAT_FAILURE: getType('CREATE_CHAT_FAILURE'),

  SET_ACTIVE_CHAT: getType('SET_ACTIVE_CHAT'),
};
