const getType = key => Symbol(`WS/${key}`);

export default {
  WS_CONNECTION_REQUEST: getType('WS_CONNECTION_REQUEST'),
  WS_CONNECTION_SUCCESS: getType('WS_CONNECTION_SUCCESS'),
  WS_CONNECTION_FAILURE: getType('WS_CONNECTION_FAILURE'),

  WS_SEND_MESSAGE: getType('WS_SEND_MESSAGE'),
  WS_RECEIVE_MESSAGE: getType('WS_RECEIVE_MESSAGE'),
  WS_RECEIVE_NEW_CHAT: getType('WS_RECEIVE_NEW_CHAT'),
  WS_RECEIVE_DELETED_CHAT: getType('WS_RECEIVE_DELETED_CHAT'),
};
