const getType = key => Symbol(`sockets/${key}`);

export default {
  WS_CONNECTION_REQUEST: getType('WS_CONNECTION_REQUEST'),
  WS_CONNECTION_SUCCESS: getType('WS_CONNECTION_SUCCESS'),
  WS_CONNECTION_FAILURE: getType('WS_CONNECTION_FAILURE'),
  WS_CONNECTION_CLOSE: getType('WS_CONNECTION_CLOSE'),

  WS_SEND_MESSAGE_REQUEST: getType('WS_SEND_MESSAGE_REQUEST'),
  WS_SEND_MESSAGE_SUCCESS: getType('WS_SEND_MESSAGE_SUCCESS'),

  WS_RECEIVE_MESSAGE: getType('WS_RECEIVE_MESSAGE'),
  WS_RECEIVE_NEW_CHAT: getType('WS_RECEIVE_NEW_CHAT'),
  WS_RECEIVE_DELETED_CHAT: getType('WS_RECEIVE_DELETED_CHAT'),

  WS_MOUNT_CHAT: getType('WS_MOUNT_CHAT'),
  WS_UNMOUNT_CHAT: getType('WS_UNMOUNT_CHAT'),
};
